
{% set name = "django-versatileimagefield" %}
{% set version = "1.11" %}
{% set sha256 = "8322ee9d7bf5ffa5360990320d2cc2efc7017feff35422636d49f625721edf82" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - pillow >=2.4.0,<6.0.0
    
test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(INSTALLED_APPS=['versatileimagefield']); django.setup(); import versatileimagefield; import versatileimagefield.datastructures"
    

about:
  home: https://github.com/respondcreate/django-versatileimagefield
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'   #https://github.com/respondcreate/django-versatileimagefield/issues/107
  summary: 'A drop-in replacement for django ImageField that
  provides a flexible, intuitive and easily-extensible interface 
  for quickly creating new images from the one assigned to the field.'
  description: |
    A drop-in replacement for django's ImageField that provides a 
    flexible, intuitive and easily-extensible interface for creating 
    new images from the one assigned to the field.
  doc_url: https://django-versatileimagefield.readthedocs.io/en/latest/
  dev_url: https://github.com/respondcreate/django-versatileimagefield

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
