
{% set name = "django-versatileimagefield" %}
{% set version = "1.9" %}
{% set sha256 = "2ebdd7125cc0e275a52d1119ae1fabefd76797c9de11f26099eb427f34f0c382" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - pillow ==4.0.0
    
test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(INSTALLED_APPS=['versatileimagefield']); django.setup(); import versatileimagefield; import versatileimagefield.datastructures"
    

about:
  home: https://github.com/respondcreate/django-versatileimagefield
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'   #https://github.com/respondcreate/django-versatileimagefield/issues/107
  summary: 'A drop-in replacement for django ImageField that
  provides a flexible, intuitive and easily-extensible interface 
  for quickly creating new images from the one assigned to the field.'
  description: |
    A drop-in replacement for django's ImageField that provides a 
    flexible, intuitive and easily-extensible interface for creating 
    new images from the one assigned to the field.
  doc_url: https://django-versatileimagefield.readthedocs.io/en/latest/
  dev_url: https://github.com/respondcreate/django-versatileimagefield

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
