travis:
  secure:
    BINSTAR_TOKEN: a1KasMrTZVGCCu0iuMpfWlu/X1dnrgqSNfmqLXiOWw8lVqSI2/IoOGniEC3LrJXdKgIlFzOhsFzsNgrWbcvL75WxEmv8BuVb2WV7c0ndfEjdmjzFxI0d38C85EcDGpjjazM3xfFdwai0Kj6f3zK8bjaeN+c+5ofbth0ftFvzMd2Dcf0L5aTQL4OPGB46JHW6y0vs+njPibDfxMpb6vpnDxaQZHRm4lkQnNbi/O0ImOZL1NiF4soLzzG6+wEPDwlq7ulQ5nY48NMm3Noe2iME82tJdQnYo3KA7+AtDGC6enH2FM0Y2SxuCHSBBj5tTccGT6Dgfz185gGgI0iHcuGqiyK6CxIScdcfqdn5Oce9Mi9LCW2MRrBRsEHRFwWX/9vpjY8klp7mAk2WEadX7qUGZoxnd+hrZxjfyR3tk8UyEMw1ayyYYeacCIJWoqIyNIgkFWmbU9XzDj2PDDUiutxpNYnRwo7cqvxnlSO18uHVN6WcNue+HQn1sm4ga0a4AdN9h3aK1HZZ3mPT2YJnHQwbzn6jIh3oufJqw328mXFdO3haXbZxLk8U+5Tugklsit34GRKz3ByhuyZSmZ0wH4rdk6q11221KrW6umVrze9sdW8ZIScTJjO2ObOeUkwfLMBva5PvjD3m3XoEu12yPCyGYzHQI44NWnffp9UKuOdL9hg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
