travis:
  secure:
    BINSTAR_TOKEN: lVyCbuHcqQGqoU29Vm1wkBssQ5n3TEIyrA0TlMJjYiI6iA0XUp3+50TVgv8I7QpbW4kf2/Z/6lGGJ+yeiCwtXYhyHC0oZ5jpwN4lHR5cB6YrmiZFK4LxyO/P34zg/WK9cyDuR+G4QaMetZYfAw7fRrZCMFVeqvk1eBBd78BR68tOuTgdBc1banVgjmelv2Sqi+TGeO2FvwBu4z6E9gEkT38pBx71kOl3MEJCAIs8xzlhUx9iRavgSxr8LUZSFuZd5M3j0NSfpHgh5pYO84Ee0MuTG06IFTNdyyvaowFsWSoNWBhWyufDlPqpjcH9dz9VVBVWFWYKaUn2aLJOaAxHC+ww72T0iYIjsZryVhpCy8t8ipl7n442Y+vhGQDU6kME+pbnwbNzdVLOQF3qlue9ZF4qV6B0EaV0CI0edtAkqV06AgGuG9FAHF1fI+nvPl9IlTBShrBTusymyE36xWrUnqOXXcx9/tYzwXxaHAqr7R3CQUMUyJdlbY97kvnwO1g9ovhcX9kYksRivbPFKBD6F+XhgSkLCsQ6eW2woTv1tHPZ8aQYIA1+8UbCHGY86B2gI3+npNLO14K6Kuu1RoHZL2DgZTTweKgn1uZS2EGj6kNYCIKkGlauWhRZRRITusXLn05i0+rsFnADZxHA1/xQDoLh5lYLCedefq/HzmipmEQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
