travis:
  secure:
    BINSTAR_TOKEN: Jg7zWlFQjVDxLaLajtPMPZwaeHnWxM1OMJydyqkHVkVjhP4ZhjZSwA12kzJL0MW/akve6LXSbJWlQ2R2cdnYt7FaE4CB8KbL3PNNnqBPTCZbw1swDyUfp5xhxQgKUh4xkVrUhkxGaFrwwCR15Tdt2TQqB+JnEoEIr7fW++PV1d9TwepjV/ehJ0vhIze5fmKOltv7SufJGPbKzSdVGfH3xdTWxURXXRafDc9rSgpEj2UtuXcW+A+FlBf9DmhxocSTUWaqXtEqsfGnrD2NDAGQyxGKyyr8XSBl8xO5qAmZB5Jm9ga+bL6Mqs1cWin2u4MNhJMgAYve3abIfEj8IzKo6rRH5QBkv4Hcwvzez/t7XuEb7iubFhHkbYz2Mm7nbKEKeshJGLZEIQYKRsXfRwmlk9LHFxlcrF9SZckxaikMgiQqR6QeshhdP3PoJGvbpOfTkZvbkE66rFNr6PNCAG4E+COw3BpUFO8oC9ad7x802e8jv/5qeRWqrjXTZmLXKoPIiD7InIVgGh7G/3bNjjGQqTg/DXxhHhsj6E2S319nqewXNoUPtHw4HnJkrhKmN9nV6ugvShQYozXW12zkYyPOFJ2/avG5P7IF//KNZp//98Lbdm78ZzFe2n2LzwJIZRsenAHrCy6irdy18OKMrUNRLInh3jUHuaGX/7QY6sZyw90=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
